server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://115.175.45.173:5432/deeptalk
    username: postgres
    password: DeepTalk@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 